"""Generate Obsidian CSS snippet and graph color groups for topic color-coding.

Reads topics from the manifest, assigns each a unique HSL hue, and writes:
1. A CSS snippet to ``wiki/.obsidian/snippets/topic-colors.css`` for note styling.
2. Color groups into ``wiki/.obsidian/graph.json`` for graph view coloring.
"""

from __future__ import annotations

import colorsys
import json
import re
from pathlib import Path

from core.manifest import Manifest


def _slugify(text: str) -> str:
    """Lowercase, replace spaces/underscores with hyphens, strip non-alnum."""
    s = text.lower().strip()
    s = re.sub(r"[\s_]+", "-", s)
    s = re.sub(r"[^a-z0-9-]", "", s)
    return s.strip("-")


def _hsl_to_rgb_int(h: float, s: float, l: float) -> int:
    """Convert HSL (h in degrees, s/l in 0-100) to Obsidian's decimal RGB int."""
    r, g, b = colorsys.hls_to_rgb(h / 360, l / 100, s / 100)
    return (round(r * 255) << 16) | (round(g * 255) << 8) | round(b * 255)


def generate_snippet(manifest: Manifest, wiki_dir: Path) -> Path:
    """Generate the Obsidian CSS snippet and graph colors. Return CSS path."""
    topics = manifest.list_topics()

    if not topics:
        css = (
            "/* Auto-generated by llm_wiki — no topics found yet. */\n"
            "/* Ingest documents, then run the theme command again. */\n"
        )
    else:
        css = _build_css(topics)

    snippets_dir = wiki_dir / ".obsidian" / "snippets"
    snippets_dir.mkdir(parents=True, exist_ok=True)

    out = snippets_dir / "topic-colors.css"
    out.write_text(css)

    # Generate graph view color groups
    if topics:
        _write_graph_colors(topics, wiki_dir)

    return out


def _write_graph_colors(topics: dict[str, list[str]], wiki_dir: Path) -> None:
    """Write color groups into .obsidian/graph.json for graph view."""
    obsidian_dir = wiki_dir / ".obsidian"
    graph_path = obsidian_dir / "graph.json"

    # Load existing graph config to preserve other settings
    if graph_path.exists():
        try:
            config = json.loads(graph_path.read_text())
        except (json.JSONDecodeError, ValueError):
            config = {}
    else:
        config = {}

    n = len(topics)
    color_groups = []
    for i, (topic, _) in enumerate(sorted(topics.items())):
        hue = round((i * 360) / n) % 360
        rgb_int = _hsl_to_rgb_int(hue, 60, 48)
        slug = _slugify(topic)
        color_groups.append({
            "query": f"tag:#topic/{slug}",
            "color": {"a": 1, "rgb": rgb_int},
        })

    config["colorGroups"] = color_groups
    config["collapse-color-groups"] = False
    graph_path.write_text(json.dumps(config, indent=2) + "\n")


def _build_css(topics: dict[str, list[str]]) -> str:
    """Build the full CSS string for all topics."""
    n = len(topics)
    lines = [
        "/* Auto-generated by llm_wiki — regenerate with: */",
        "/* uv run python cli.py --dir <wiki> theme       */",
        "/* Enable in Obsidian: Settings > Appearance > CSS snippets > topic-colors */",
        "",
    ]

    for i, (topic, subtopics) in enumerate(sorted(topics.items())):
        hue = round((i * 360) / n) % 360
        slug = _slugify(topic)
        cls = f"topic-{slug}"

        lines.append(f"/* ── {topic} ── */")
        lines.append(f".{cls} {{")
        lines.append(f"  border-left: 4px solid hsl({hue}, 60%, 48%) !important;")
        lines.append(f"  padding-left: 12px !important;")
        lines.append(
            f"  background: linear-gradient("
            f"90deg, hsla({hue}, 60%, 48%, 0.06) 0%, transparent 30%"
            f") !important;"
        )
        lines.append("}")

        # Subtopic-specific overrides: vary lightness for each subtopic
        m = len(subtopics)
        for j, sub in enumerate(subtopics):
            lightness = 38 + round((j * 24) / max(m - 1, 1))
            sub_slug = _slugify(sub)
            # Additional class for granular styling via Dataview or future use
            lines.append(f".{cls}.subtopic-{sub_slug} {{")
            lines.append(f"  border-left-color: hsl({hue}, 60%, {lightness}%) !important;")
            lines.append(
                f"  background: linear-gradient("
                f"90deg, hsla({hue}, 60%, {lightness}%, 0.06) 0%, transparent 30%"
                f") !important;"
            )
            lines.append("}")

        lines.append("")

    # Legend comment at the bottom for reference
    lines.append("/* ── Color legend ── */")
    for i, (topic, _) in enumerate(sorted(topics.items())):
        hue = round((i * 360) / n) % 360
        lines.append(f"/* {topic:30s} → hsl({hue}, 60%, 48%) */")

    lines.append("")
    return "\n".join(lines)
